name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./TPO
      - name: Run test (Coverage > 85% since Exercise 4)
        run: mvn -B test --file pom.xml
        working-directory: ./TPO
