name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./TPO
      - name: Run test (Coverage > 85% since Exercise 4)
        run: mvn -B test --file pom.xml
        working-directory: ./TPO
      - name: Publish test coverage results
        uses: madrapps/jacoco-report@v1.3
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          min-coverage-overall: 80
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          working-directory: ./TPO
      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')