name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        working-directory: ./TPO
        run: mvn -B install --file pom.xml
      - name: Publish test coverage results
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: 'TPO/target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          minimum_coverage: 80
          fail_below_threshold: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Publish Coverage Job Summary
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
